[package]
name = "memdb"
version = "0.1.0"
authors = ["Ifeanyi Ubah <http://www.ifeanyi.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.2"
